### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by modev** [CentauriCloud/CentauriCloud#12]
A logging implementation would be great for debugging and live systems. How far this should be taken is open for discussion. 
Think the best way to do this is writing a own "Logger" module. The configuration for this module should be as flexible as possible. The user should be able to say which events should get logged and how they are logged (console, file, remote dest., etc).

**Comment by Microsamp** [comment]
https://www.slf4j.org/ and log4j

**Comment by Microsamp** [comment]
See Centauri-Logger
