### ISSUE TITLE
Update old configs without re-copy the default config

### ISSUE THREAD

**Issue by Microsamp** [CentauriCloud/CentauriCloud#25]
At this moment, users have to delete their config, if they want to update the master. Only re-creating creates new keys.

We have to "update" the configuration with new keys without create new code for every key/value.

**Comment by jsauvain** [comment]
Compare the keys with the default config to the users config

**Comment by LordOtut** [comment]
added with https://github.com/CentauriCloud/CentauriCloud/commit/462f7caf5d08ae7493a8761ca4fed4e4e6fad84c
@jsauvain @Microsamp
