### ISSUE TITLE
Client netty impl.

### ISSUE THREAD

**Issue by Microsamp** [CentauriCloud/CentauriCloud#3]
Implement netty into the client

**Comment by Microsamp** [comment]
@jsauvain I am permitted to rename the "connector" to an spigot and one BungeeCord implementation?

**Comment by jsauvain** [comment]
SpigotConnector & BungeeConnector & (DaemonConnector)

**Comment by jsauvain** [comment]
Probably we could use one connector for all. They do pretty the same so we do not have to rewrite same code. We could easily implement one class extending JavaPlugin and another extending Plugin

**Comment by Microsamp** [comment]
The spigot-connector is full implemented
