### ISSUE TITLE
Shared files improvements

### ISSUE THREAD

**Issue by modev** [CentauriCloud/CentauriCloud#43]
Shared files would be much more useful if they were a little bit more flexible. Currently they are being copied, with the same name. This makes it impossible to have multiple plugin configurations (for example a worldedit config for a lobby template and one for a buildserver template). It would be much more useful if it was possible to specify the source and the target filename instead of the source and the target filename being exactly the same. 

Unfortunately, I guess this is not possible by using properties configuration. But a JSON configuration would do the job just fine. 
```json
{
  "sharedFiles": {
    "source-config.yml": "plugins/plugin/config.yml"
  }
}
```

**Comment by Microsamp** [comment]
I will think about it.

**Comment by Microsamp** [comment]
https://github.com/CentauriCloud/CentauriCloud/commit/00a675652ef15a8e10e0c6daab5740044806927b
