### ISSUE TITLE
Bungeecord-Connector compatibility trouble

### ISSUE THREAD

**Issue by PrexorJustin** [CentauriCloud/CentauriCloud#68]
It seems like the connector has problems with the compatibility of the latest version of Bungeecord. The Connector cant initialize the Logger. #

**Comment by Microsamp** [comment]
From BungeeCord:
>     * Called when the plugin has just been loaded. Most of the proxy will not
>     * be initialized, so only use it for registering
>     * {@link ConfigurationAdapter}'s and other predefined behavior.

We have to initalize our logger instance on #onEnable .

Should we use "System.out" for debug messages @jsauvain on #onLoad?
